### ISSUE TITLE
Selecionar todos produtos no /admin não está funcionando

### ISSUE THREAD

**Issue by luizcn** [tiagocordeiro/zumaq-partners#348]
Lembro que antes estava normal, conseguia apertar no tickzinho que selecionava todos. Agora o tick não funciona, e também tem um botão lá que diz "Selecionar todos" que não está funcionando.

**Comment by tiagocordeiro** [comment]
Você pode testar novamente?
Alguns arquivos javascript não estavam carregando. Rodei um collectstatic e aparentemente está OK
![Captura de Tela 2020-02-27 às 11 56 10](https://user-images.githubusercontent.com/6535995/75455579-4eaa5000-5958-11ea-9a88-b32468638901.png)
