### ISSUE TITLE
Fator Revenda

### ISSUE THREAD

**Issue by loboluiz** [tiagocordeiro/zumaq-partners#36]
Um fator personalizado para cada cadastro de revendedor que altere os fatores padrões, e que ao acrescentar um fator para determinado produto seja substituído.

**Comment by tiagocordeiro** [comment]
Agora você pode configurar um coeficiente padrão para o parceiro.
Além de poder adicionar um coeficiente personalizado por produto.

Coeficiente padrão: 50% (0.50)
