### ISSUE TITLE
Remover Produtos

### ISSUE THREAD

**Issue by loboluiz** [tiagocordeiro/zumaq-partners#41]
Não existe um jeito fácil de remover os produtos já cadastrados no sistema. Pode ser um botão dentro do produto, ou um esquema de selecionar os produtos e usar uma "ação" de remover.

**Comment by tiagocordeiro** [comment]
Foi configurado uma forma de desabilitar/habilitar o produto.
Quando o produto é criado, o 'status' é inativo.
Automaticamente redireciona para página de produto:update, onde pode ser habilitado.
Assim não corremos o risco de ter problemas futuros consultando um pedido que possui item que foi removido.
