### ISSUE TITLE
Preview de Preço no Produto

### ISSUE THREAD

**Issue by loboluiz** [tiagocordeiro/zumaq-partners#42]
Ao editar ou criar um produto, temos que ficar salvando o produto e indo ver na tabela. Seria interessante ao modificar um coeficiente, por exemplo, ele já dar um preview do preço antes de salvar.

**Comment by tiagocordeiro** [comment]
Ok, vou criar uma nova branch para isso. Provavelmente faremos no frontend com javascript.

Por enquanto, alterei o cadastro e atualização de produto para quando salvo, recarregar a página com os dados atualizados.
