### ISSUE TITLE
Separação e conferencia de pedidos

### ISSUE THREAD

**Issue by tiagocordeiro** [tiagocordeiro/zumaq-partners#643]
Deve ser possível para um operador usar um pedido recebido para separação e conferencia dos itens pedidos.

Deve ser possível para um operador adicionar a cada item do pedido informações como notas e imagens além de dados como usuário/operador, data e hora que o pedido foi separado.

**Comment by hugo-chaves** [comment]
de acordo exatamente as alterações necessarias
